import { Toaster } from 'react-hot-toast';
import "./globals.css";

export const metadata = {
  title: "Feedback Collector",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
